# Auto-generated by release-update-homebrew — do not edit by hand.
class Agentvisor < Formula
  desc "Manetu AgentVisor — secure runtime for AI agents"
  homepage "https://github.com/manetu/agentvisor"
  version "0.5.0-54.200"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/manetu/agentvisor/releases/download/v0.5.0-54.200/agentvisor-darwin-arm64-v0.5.0-54.200.tar.gz"
      sha256 "be763e081de28875e4ca16be7b666c402362e0760987676ddefe9087910e258f"
    end
    on_intel do
      url "https://github.com/manetu/agentvisor/releases/download/v0.5.0-54.200/agentvisor-darwin-amd64-v0.5.0-54.200.tar.gz"
      sha256 "dca99c222a3f50c7ef802f38abb83ff546f645e5cac02f851a65b25a2e2609e8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/manetu/agentvisor/releases/download/v0.5.0-54.200/agentvisor-linux-arm64-v0.5.0-54.200.tar.gz"
      sha256 "9824ea4aa6ba31a0933d8f447f09bf6f8658de6496d9159e911755b60bc30105"
    end
    on_intel do
      url "https://github.com/manetu/agentvisor/releases/download/v0.5.0-54.200/agentvisor-linux-amd64-v0.5.0-54.200.tar.gz"
      sha256 "fa4b9cd9d584caacc9f4c59f37eb57a634bec2ef2aa0a0ed7d73ac41248184f4"
    end
  end

  def install
    bin.install "agentvisor"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentvisor version")
  end
end
