# Auto-generated by release-update-homebrew — do not edit by hand.
class Agentvisor < Formula
  desc "Manetu AgentVisor — secure runtime for AI agents"
  homepage "https://github.com/manetu/agentvisor"
  version "0.6.0-6.217"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/manetu/agentvisor/releases/download/v0.6.0-6.217/agentvisor-darwin-arm64-v0.6.0-6.217.tar.gz"
      sha256 "6a3187da9040becd1b6194126bb49967de6ab41814e3fcebdeb0a1320770a998"
    end
    on_intel do
      url "https://github.com/manetu/agentvisor/releases/download/v0.6.0-6.217/agentvisor-darwin-amd64-v0.6.0-6.217.tar.gz"
      sha256 "5369d29c33ff95ac3291f54f2a59b270a8af3da52e2996c555b2e18a89cf8dee"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/manetu/agentvisor/releases/download/v0.6.0-6.217/agentvisor-linux-arm64-v0.6.0-6.217.tar.gz"
      sha256 "75e45b0cc5628202a8c08d7c13426a60f508b7aef5bb5a433612221a25b48630"
    end
    on_intel do
      url "https://github.com/manetu/agentvisor/releases/download/v0.6.0-6.217/agentvisor-linux-amd64-v0.6.0-6.217.tar.gz"
      sha256 "758453d334ed5ff62349d194a2089b47c09ff30ee9c552b5727e5352b129f4fc"
    end
  end

  def install
    bin.install "agentvisor"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentvisor version")
  end
end
