# Auto-generated by release-update-homebrew — do not edit by hand.
class Kura < Formula
  desc "Kura — sandboxed Claude Code CLI built on Manetu AgentVisor"
  homepage "https://github.com/manetu/kura"
  version "0.1.0-6.14"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/manetu/kura/releases/download/v0.1.0-6.14/kura-darwin-arm64-v0.1.0-6.14.tar.gz"
      sha256 "62832b53ea6cd51a04e799cb40507dcb9592a695009dc5d6c7e21320e8a69ce7"
    end
    on_intel do
      url "https://github.com/manetu/kura/releases/download/v0.1.0-6.14/kura-darwin-amd64-v0.1.0-6.14.tar.gz"
      sha256 "45bb8256c4826a8a865e1c286266f3131a5ca2f0fdf3f8011f605ff575af8984"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/manetu/kura/releases/download/v0.1.0-6.14/kura-linux-arm64-v0.1.0-6.14.tar.gz"
      sha256 "e5eade08f1be1547cad4ef90bdd842996b20a16bb3162f0c869bb13624b8d60c"
    end
    on_intel do
      url "https://github.com/manetu/kura/releases/download/v0.1.0-6.14/kura-linux-amd64-v0.1.0-6.14.tar.gz"
      sha256 "5c7032a0ea8149eb27cd378e33b9ece845af199904306fc153a655ae34fc7132"
    end
  end

  def install
    bin.install "kura"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kura version")
  end
end
