# Auto-generated by release-update-homebrew — do not edit by hand.
class Kura < Formula
  desc "Kura — sandboxed Claude Code CLI built on Manetu AgentVisor"
  homepage "https://github.com/manetu/kura"
  version "0.1.0-3.7"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/manetu/kura/releases/download/v0.1.0-3.7/kura-darwin-arm64-v0.1.0-3.7.tar.gz"
      sha256 "685eb47807b25554189dfe4ad67800edf7f868684b3d4a73ebdaf3f103aae7e3"
    end
    on_intel do
      url "https://github.com/manetu/kura/releases/download/v0.1.0-3.7/kura-darwin-amd64-v0.1.0-3.7.tar.gz"
      sha256 "d14298d1280808523aa05018808cad1599cc64b0618e9a3d8441741ed0a78bc7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/manetu/kura/releases/download/v0.1.0-3.7/kura-linux-arm64-v0.1.0-3.7.tar.gz"
      sha256 "763adb4c13a0341040aa866869106e3a33e91ace078a5ab3c10ffe6746f40cd5"
    end
    on_intel do
      url "https://github.com/manetu/kura/releases/download/v0.1.0-3.7/kura-linux-amd64-v0.1.0-3.7.tar.gz"
      sha256 "e710142ba64e58b74cca0a93ca5b883c29363a0e1238bacdbd7426cde4a27393"
    end
  end

  def install
    bin.install "kura"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kura version")
  end
end
